import { defineStore } from 'pinia'

// 多语言翻译
const translations = {
  en: {
    // Common
    home: 'Home',
    dashboard: 'Dashboard',
    projects: 'Projects',
    settings: 'Settings',
    search: 'Search',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    copy: 'Copy',
    create: 'Create',
    add: 'Add',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No Data',
    confirm: 'Confirm',
    actions: 'Actions',
    active: 'Active',
    copyUrl: 'Copy URL',
    testConnection: 'Test Connection',
    testing: 'Testing...',
    connected: 'Connected',
    connectionFailed: 'Connection failed',
    creating: 'Creating...',
    createProject: 'Create Project',
    manageInstances: 'Manage your Meilisearch instances',
    noProjects: 'No Projects',
    noProjectsDesc: 'Add your first Meilisearch instance to get started.',
    masterApiKey: 'Master API Key',
    optional: 'optional',
    optionalDesc: 'Optional description',
    required: 'required',
    notSet: 'Not set',
    updated: 'Updated',
    preview: 'Preview',
    deleting: 'Deleting...',
    adding: 'Adding...',
    addDocuments: 'Add Documents',
    jsonDocuments: 'JSON Documents',
    deleteConfirm: 'Are you sure you want to delete',
    cannotUndo: 'This action cannot be undone.',
    projectNotFound: 'Project Not Found',
    projectNotFoundDesc: "The project you're looking for doesn't exist.",
    uidHint: 'Must start with a letter, can contain letters, numbers, underscores, and hyphens.',
    primaryKeyHint: 'The primary key will be inferred from the first document if not set.',
    saving: 'Saving...',
    searching: 'Searching...',
    
    // Project
    addProject: 'Add Project',
    projectName: 'Project Name',
    projectUrl: 'Meilisearch URL',
    apiKey: 'API Key',
    description: 'Description',
    indexes: 'Indexes',
    documents: 'Documents',
    searches: 'Searches',
    tasks: 'Tasks',
    keys: 'API Keys',
    searchPreview: 'Search Preview',
    
    // Index
    createIndex: 'Create Index',
    indexUid: 'Index UID',
    primaryKey: 'Primary Key',
    general: 'General',
    attributes: 'Attributes',
    rankingRules: 'Ranking Rules',
    synonyms: 'Synonyms',
    typoTolerance: 'Typo Tolerance',
    prefixSearch: 'Prefix Search',
    stopWords: 'Stop Words',
    separators: 'Separators',
    dictionary: 'Dictionary',
    pagination: 'Pagination',
    faceting: 'Faceting',
    searchCutoff: 'Search Cutoff',
    embedders: 'Embedders',
    noIndexes: 'No Indexes',
    noIndexesDesc: 'Create your first index to start indexing documents.',
    indexNotFound: 'Index Not Found',
    indexNotFoundDesc: "The index you're looking for doesn't exist.",
    deleteIndex: 'Delete Index',
    
    // Search
    searchDocuments: 'Search documents...',
    results: 'results',
    noResults: 'No results found',
    sortBy: 'Sort by...',
    filters: 'Filters',
    tableView: 'Table View',
    jsonView: 'JSON View',
    rankingScore: 'Ranking Score',
    copyJson: 'Copy JSON',
    editDocument: 'Edit Document',
    deleteDocument: 'Delete Document',
    selectColumns: 'Select Columns',
    selectIndex: 'Select Index',
    columns: 'Columns',
    score: 'Score',
    selectAnIndex: 'Select an Index',
    selectAnIndexDesc: 'Choose an index to start searching.',
    
    // Tasks
    status: 'Status',
    type: 'Type',
    index: 'Index',
    uid: 'UID',
    duration: 'Duration',
    date: 'Date',
    applyFilters: 'Apply Filters',
    reset: 'Reset',
    noTasks: 'No Tasks',
    noTasksDesc: 'No tasks match the current filters.',
    taskDetails: 'Task Details',
    enqueuedAt: 'Enqueued At',
    fullDetails: 'Full Details',
    error: 'Error',
    showingTasks: 'Showing {count} tasks',
    loadMore: 'Load More',
    
    // Keys
    apiKeys: 'API Keys',
    createKey: 'Create Key',
    unnamedKey: 'Unnamed Key',
    noDescription: 'No description',
    copyKey: 'Copy Key',
    key: 'Key',
    createdAt: 'Created At',
    expiresAt: 'Expires At',
    never: 'Never',
    noApiKeys: 'No API Keys',
    noApiKeysDesc: 'Create API keys to access your Meilisearch instance.',
    createApiKey: 'Create API Key',
    name: 'Name',
    uidOptional: 'UID (optional)',
    customUid: 'Custom UID',
    actionsRequired: 'Actions *',
    indexesRequired: 'Indexes *',
    indexesHint: 'Use * for all indexes, or comma-separated index names',
    deleteApiKey: 'Delete API Key',
    deleteApiKeyConfirm: 'Are you sure you want to delete this API key? This action cannot be undone.',
    
    // Settings Page
    basicInfo: 'Basic Information',
    saveChanges: 'Save Changes',
    instanceInfo: 'Instance Information',
    version: 'Version',
    databaseSize: 'Database Size',
    healthy: 'Healthy',
    unhealthy: 'Unhealthy',
    dangerZone: 'Danger Zone',
    deleteProject: 'Delete Project',
    deleteProjectDesc: 'Remove this project from Meilisearch Admin. This will not delete the actual Meilisearch instance.',
    deleteProjectConfirm: 'Are you sure you want to delete this project? This action cannot be undone.',
    connectionSuccess: 'Connection successful!',
    connectionFailedMsg: 'Connection failed',
    
    // Home Page
    welcomeTitle: 'Welcome to Meilisearch Admin',
    welcomeDesc: 'A powerful web-based administration interface for managing your Meilisearch instances. Add projects, manage indexes, configure settings, and preview search results.',
    totalProjects: 'Total Projects',
    activeInstances: 'Active Instances',
    quickAction: 'Quick Action',
    viewAllProjects: 'View All Projects',
    recentProjects: 'Recent Projects',
    viewAll: 'View All',
    noProjectsYet: 'No Projects Yet',
    noProjectsYetDesc: 'Get started by adding your first Meilisearch instance.',
    
    // Index General Page
    fieldDistribution: 'Field Distribution',
    indexing: 'Indexing',
    deleteAllDocuments: 'Delete All Documents',
    deleteAllDocsConfirm: 'Are you sure you want to delete all documents from this index?',
    deleteAll: 'Delete All',
    deleteIndexConfirm: 'Are you sure you want to delete this index? This action cannot be undone.',
    
    // Theme
    theme: 'Theme',
    themeTech: 'Tech',
    themePink: 'Pink',
    themeDark: 'Dark',
    themeLight: 'Light',
    language: 'Language',
  },
  zh: {
    // Common
    home: '首页',
    dashboard: '仪表盘',
    projects: '项目',
    settings: '设置',
    search: '搜索',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    copy: '复制',
    create: '创建',
    add: '添加',
    close: '关闭',
    loading: '加载中...',
    noData: '暂无数据',
    confirm: '确认',
    actions: '操作',
    active: '活跃',
    copyUrl: '复制地址',
    testConnection: '测试连接',
    testing: '测试中...',
    connected: '已连接',
    connectionFailed: '连接失败',
    creating: '创建中...',
    createProject: '创建项目',
    manageInstances: '管理您的 Meilisearch 实例',
    noProjects: '暂无项目',
    noProjectsDesc: '添加您的第一个 Meilisearch 实例开始使用。',
    masterApiKey: '主API密钥',
    optional: '可选',
    optionalDesc: '选填描述信息',
    required: '必填',
    notSet: '未设置',
    updated: '更新于',
    preview: '预览',
    deleting: '删除中...',
    adding: '添加中...',
    addDocuments: '添加文档',
    jsonDocuments: 'JSON文档',
    deleteConfirm: '确定要删除',
    cannotUndo: '此操作无法撤销。',
    projectNotFound: '项目未找到',
    projectNotFoundDesc: '您查找的项目不存在。',
    uidHint: '必须以字母开头，可包含字母、数字、下划线和连字符。',
    primaryKeyHint: '如未设置，主键将从第一个文档中推断。',
    saving: '保存中...',
    searching: '搜索中...',
    
    // Project
    addProject: '添加项目',
    projectName: '项目名称',
    projectUrl: 'Meilisearch 地址',
    apiKey: 'API密钥',
    description: '描述',
    indexes: '索引',
    documents: '文档',
    searches: '搜索',
    tasks: '任务',
    keys: 'API密钥',
    searchPreview: '搜索预览',
    
    // Index
    createIndex: '创建索引',
    indexUid: '索引名称',
    primaryKey: '主键',
    general: '基础信息',
    attributes: '属性',
    rankingRules: '排序规则',
    synonyms: '同义词',
    typoTolerance: '容错设置',
    prefixSearch: '前缀搜索',
    stopWords: '停止词',
    separators: '分隔符',
    dictionary: '字典',
    pagination: '分页',
    faceting: '分面',
    searchCutoff: '搜索截止',
    embedders: '向量化',
    noIndexes: '暂无索引',
    noIndexesDesc: '创建您的第一个索引以开始索引文档。',
    indexNotFound: '索引未找到',
    indexNotFoundDesc: '您查找的索引不存在。',
    deleteIndex: '删除索引',
    
    // Search
    searchDocuments: '搜索文档...',
    results: '条结果',
    noResults: '未找到结果',
    sortBy: '排序方式...',
    filters: '筛选',
    tableView: '表格视图',
    jsonView: 'JSON视图',
    rankingScore: '相关度评分',
    copyJson: '复制JSON',
    editDocument: '编辑文档',
    deleteDocument: '删除文档',
    selectColumns: '选择列',
    selectIndex: '选择索引',
    columns: '列',
    score: '评分',
    selectAnIndex: '请选择索引',
    selectAnIndexDesc: '选择一个索引开始搜索。',
    
    // Tasks
    status: '状态',
    type: '类型',
    index: '索引',
    uid: 'UID',
    duration: '耗时',
    date: '日期',
    applyFilters: '应用筛选',
    reset: '重置',
    noTasks: '暂无任务',
    noTasksDesc: '没有符合当前筛选条件的任务。',
    taskDetails: '任务详情',
    enqueuedAt: '入队时间',
    fullDetails: '完整详情',
    error: '错误',
    showingTasks: '显示 {count} 条任务',
    loadMore: '加载更多',
    
    // Keys
    apiKeys: 'API密钥',
    createKey: '创建密钥',
    unnamedKey: '未命名密钥',
    noDescription: '暂无描述',
    copyKey: '复制密钥',
    key: '密钥',
    createdAt: '创建时间',
    expiresAt: '过期时间',
    never: '永不过期',
    noApiKeys: '暂无API密钥',
    noApiKeysDesc: '创建API密钥以访问您的Meilisearch实例。',
    createApiKey: '创建API密钥',
    name: '名称',
    uidOptional: 'UID（可选）',
    customUid: '自定义UID',
    actionsRequired: '操作权限 *',
    indexesRequired: '索引权限 *',
    indexesHint: '使用 * 表示所有索引，或用逗号分隔的索引名称',
    deleteApiKey: '删除API密钥',
    deleteApiKeyConfirm: '确定要删除此API密钥吗？此操作无法撤销。',
    
    // Settings Page
    basicInfo: '基本信息',
    saveChanges: '保存更改',
    instanceInfo: '实例信息',
    version: '版本',
    databaseSize: '数据库大小',
    healthy: '健康',
    unhealthy: '不健康',
    dangerZone: '危险区域',
    deleteProject: '删除项目',
    deleteProjectDesc: '从Meilisearch Admin中移除此项目。这不会删除实际的Meilisearch实例。',
    deleteProjectConfirm: '确定要删除此项目吗？此操作无法撤销。',
    connectionSuccess: '连接成功！',
    connectionFailedMsg: '连接失败',
    
    // Home Page
    welcomeTitle: '欢迎使用 Meilisearch Admin',
    welcomeDesc: '强大的基于Web的管理界面，用于管理您的Meilisearch实例。添加项目、管理索引、配置设置并预览搜索结果。',
    totalProjects: '项目总数',
    activeInstances: '活跃实例',
    quickAction: '快捷操作',
    viewAllProjects: '查看所有项目',
    recentProjects: '最近项目',
    viewAll: '查看全部',
    noProjectsYet: '暂无项目',
    noProjectsYetDesc: '添加您的第一个Meilisearch实例开始使用。',
    
    // Index General Page
    fieldDistribution: '字段分布',
    indexing: '索引中',
    deleteAllDocuments: '删除所有文档',
    deleteAllDocsConfirm: '确定要删除此索引中的所有文档吗？',
    deleteAll: '全部删除',
    deleteIndexConfirm: '确定要删除此索引吗？此操作无法撤销。',
    
    // Theme
    theme: '主题',
    themeTech: '科技蓝',
    themePink: '粉红',
    themeDark: '暗黑',
    themeLight: '明亮',
    language: '语言',
  },
}

export const useSettingsStore = defineStore('settings', {
  state: () => ({
    language: localStorage.getItem('language') || 'en',
    theme: localStorage.getItem('theme') || 'tech',
  }),

  getters: {
    t: (state) => (key) => {
      return translations[state.language]?.[key] || translations.en[key] || key
    },
    
    currentLanguage: (state) => state.language,
    currentTheme: (state) => state.theme,
  },

  actions: {
    setLanguage(lang) {
      this.language = lang
      localStorage.setItem('language', lang)
    },

    setTheme(theme) {
      this.theme = theme
      localStorage.setItem('theme', theme)
      this.applyTheme(theme)
    },

    applyTheme(theme) {
      const root = document.documentElement
      
      // Remove all theme classes
      root.classList.remove('theme-tech', 'theme-pink', 'theme-dark', 'theme-light')
      
      // Add new theme class
      root.classList.add(`theme-${theme}`)
    },

    initTheme() {
      this.applyTheme(this.theme)
    },
  },
})
