import { defineStore } from 'pinia'

// 多语言翻译
const translations = {
  en: {
    // Common
    home: 'Home',
    dashboard: 'Dashboard',
    projects: 'Projects',
    settings: 'Settings',
    search: 'Search',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    copy: 'Copy',
    create: 'Create',
    add: 'Add',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No Data',
    confirm: 'Confirm',
    actions: 'Actions',
    active: 'Active',
    copyUrl: 'Copy URL',
    testConnection: 'Test Connection',
    testing: 'Testing...',
    connected: 'Connected',
    connectionFailed: 'Connection failed',
    creating: 'Creating...',
    createProject: 'Create Project',
    manageInstances: 'Manage your Meilisearch instances',
    noProjects: 'No Projects',
    noProjectsDesc: 'Add your first Meilisearch instance to get started.',
    masterApiKey: 'Master API Key',
    optional: 'optional',
    optionalDesc: 'Optional description',
    required: 'required',
    notSet: 'Not set',
    updated: 'Updated',
    preview: 'Preview',
    deleting: 'Deleting...',
    adding: 'Adding...',
    addDocuments: 'Add Documents',
    jsonDocuments: 'JSON Documents',
    uploadFile: 'Upload File',
    fetchFromUrl: 'Fetch from URL',
    selectImportMethod: 'Select Import Method',
    uploadJsonCsv: 'Upload JSON or CSV File',
    fetchDocumentsFromRemoteUrl: 'Fetch documents from a remote URL',
    file: 'File',
    chooseFile: 'Choose File',
    noFileChosen: 'No file chosen',
    remoteUrl: 'Remote URL',
    enterValidUrl: 'Enter a valid URL',
    fieldPath: 'Field Path',
    fieldPathPlaceholder: 'e.g. data.items (optional)',
    fieldPathHint: 'Specify the path to the documents array in the response, e.g. "data.results"',
    headers: 'Headers',
    headersHint: 'Additional headers to send with the request (JSON format)',
    headersPlaceholder: '{"Authorization": "Bearer ..."}',
    primaryKeyOptional: 'Primary Key (optional)',
    pasteJson: 'Paste JSON',
    upload: 'Upload',
    fetch: 'Fetch',
    import: 'Import',
    jsonTabLabel: 'JSON',
    fileTabLabel: 'File',
    urlTabLabel: 'URL',
    deleteConfirm: 'Are you sure you want to delete',
    cannotUndo: 'This action cannot be undone.',
    invalidHeadersFormat: 'Invalid headers format',
    failedToAddDocuments: 'Failed to add documents',
    projectNotFound: 'Project Not Found',
    projectNotFoundDesc: "The project you're looking for doesn't exist.",
    uidHint: 'Must start with a letter, can contain letters, numbers, underscores, and hyphens.',
    primaryKeyHint: 'The primary key will be inferred from the first document if not set.',
    saving: 'Saving...',
    searching: 'Searching...',
    
    // Project
    addProject: 'Add Project',
    projectName: 'Project Name',
    projectUrl: 'Meilisearch URL',
    apiKey: 'API Key',
    description: 'Description',
    indexes: 'Indexes',
    documents: 'Documents',
    searches: 'Searches',
    tasks: 'Tasks',
    keys: 'API Keys',
    searchPreview: 'Search Preview',
    searchControls: 'Search Controls',
    advancedSearch: 'Advanced Search',
    expandSidebar: 'Expand sidebar',
    collapseSidebar: 'Collapse sidebar',
    resizeSidebar: 'Drag to resize width',
    
    // Index
    createIndex: 'Create Index',
    indexUid: 'Index UID',
    primaryKey: 'Primary Key',
    general: 'General',
    attributes: 'Attributes',
    rankingRules: 'Ranking Rules',
    synonyms: 'Synonyms',
    typoTolerance: 'Typo Tolerance',
    prefixSearch: 'Prefix Search',
    stopWords: 'Stop Words',
    separators: 'Separators',
    dictionary: 'Dictionary',
    pagination: 'Pagination',
    faceting: 'Faceting',
    searchCutoff: 'Search Cutoff',
    embedders: 'Embedders',
    noIndexes: 'No Indexes',
    noIndexesDesc: 'Create your first index to start indexing documents.',
    indexNotFound: 'Index Not Found',
    indexNotFoundDesc: "The index you're looking for doesn't exist.",
    deleteIndex: 'Delete Index',
    
    // Search
    searchDocuments: 'Search documents...',
    results: 'results',
    noResults: 'No results found',
    sortBy: 'Sort by...',
    filters: 'Filters',
    filterType: 'Filter Type',
    equality: 'Equality',
    comparison: 'Comparison',
    addFilterAttribute: 'Add Filter Attribute',
    addSearchableAttribute: 'Add Searchable Attribute',
    addDisplayedAttribute: 'Add Displayed Attribute',
    addSortableAttribute: 'Add Sortable Attribute',
    attributeName: 'Attribute Name',
    filterMode: 'Filter Mode',
    addCondition: 'Add Condition',
    removeCondition: 'Remove Condition',
    condition: 'Condition',
    operator: 'Operator',
    value: 'Value',
    supportedOperators: 'Supported Operators',
    noFilterAttributes: 'No filter attributes configured',
    noSearchableAttributes: 'No searchable attributes configured',
    noDisplayedAttributes: 'No displayed attributes configured',
    noSortAttributes: 'No sortable attributes configured',
    selectAttribute: 'Select Attribute',
    noFilterConditions: 'No filter conditions',
    applyFilters: 'Apply Filters',
    noAvailableAttributes: 'No available attributes',
    attributeAlreadyExists: 'Attribute already exists',
    clearFilters: 'Clear Filters',
    viewMode: 'View Mode',
    enabled: 'Enabled',
    disabled: 'Disabled',
    clear: 'Clear',
    tableView: 'Table View',
    jsonView: 'JSON View',
    rankingScore: 'Ranking Score',
    copyJson: 'Copy JSON',
    copySuccess: 'Copied!',
    exportQuery: 'Export Query',
    copyCurlCommand: 'Copy cURL Command',
    exportAsPostman: 'Export for Postman',
    downloadRequestBody: 'Download Request Body',
    queryPreview: 'Query Preview',
    exportQueryDescription: 'Review your search parameters before exporting. You can copy the query body directly or export in various formats.',
    queryExported: 'Query exported!',
    copied: 'Copied!',
    downloaded: 'Downloaded!',
    exported: 'Exported!',
    close: 'Close',
    editDocument: 'Edit Document',
    deleteDocument: 'Delete Document',
    selectColumns: 'Select Columns',
    selectIndex: 'Select Index',
    columns: 'Columns',
    score: 'Score',
    selectAnIndex: 'Select an Index',
    selectAnIndexDesc: 'Choose an index to start searching.',
    
    // Tasks
    status: 'Status',
    type: 'Type',
    index: 'Index',
    uid: 'UID',
    duration: 'Duration',
    date: 'Date',
    applyFilters: 'Apply Filters',
    reset: 'Reset',
    noTasks: 'No Tasks',
    noTasksDesc: 'No tasks match the current filters.',
    taskDetails: 'Task Details',
    enqueuedAt: 'Enqueued At',
    fullDetails: 'Full Details',
    error: 'Error',
    showingTasks: 'Showing {count} tasks',
    loadMore: 'Load More',
    
    // Keys
    apiKeys: 'API Keys',
    createKey: 'Create Key',
    unnamedKey: 'Unnamed Key',
    noDescription: 'No description',
    copyKey: 'Copy Key',
    key: 'Key',
    createdAt: 'Created At',
    expiresAt: 'Expires At',
    never: 'Never',
    noApiKeys: 'No API Keys',
    noApiKeysDesc: 'Create API keys to access your Meilisearch instance.',
    createApiKey: 'Create API Key',
    name: 'Name',
    uidOptional: 'UID (optional)',
    customUid: 'Custom UID',
    actionsRequired: 'Actions *',
    indexesRequired: 'Indexes *',
    indexesHint: 'Use * for all indexes, or comma-separated index names',
    deleteApiKey: 'Delete API Key',
    deleteApiKeyConfirm: 'Are you sure you want to delete this API key? This action cannot be undone.',
    
    // Settings Page
    basicInfo: 'Basic Information',
    saveChanges: 'Save Changes',
    instanceInfo: 'Instance Information',
    version: 'Version',
    databaseSize: 'Database Size',
    healthy: 'Healthy',
    unhealthy: 'Unhealthy',
    dangerZone: 'Danger Zone',
    deleteProject: 'Delete Project',
    deleteProjectDesc: 'Remove this project from Meilisearch Admin. This will not delete the actual Meilisearch instance.',
    deleteProjectConfirm: 'Are you sure you want to delete this project? This action cannot be undone.',
    connectionSuccess: 'Connection successful!',
    connectionFailedMsg: 'Connection failed',
    
    // Home Page
    welcomeTitle: 'Welcome to Meilisearch Admin',
    welcomeDesc: 'A powerful web-based administration interface for managing your Meilisearch instances. Add projects, manage indexes, configure settings, and preview search results.',
    totalProjects: 'Total Projects',
    activeInstances: 'Active Instances',
    quickAction: 'Quick Action',
    viewAllProjects: 'View All Projects',
    recentProjects: 'Recent Projects',
    viewAll: 'View All',
    noProjectsYet: 'No Projects Yet',
    noProjectsYetDesc: 'Get started by adding your first Meilisearch instance.',
    
    // Index General Page
    fieldDistribution: 'Field Distribution',
    indexing: 'Indexing',
    deleteAllDocuments: 'Delete All Documents',
    deleteAllDocsConfirm: 'Are you sure you want to delete all documents from this index?',
    deleteAll: 'Delete All',
    deleteIndexConfirm: 'Are you sure you want to delete this index? This action cannot be undone.',
    
    // Theme
    theme: 'Theme',
    themeTech: 'Tech',
    themePink: 'Pink',
    themeDark: 'Dark',
    themeLight: 'Light',
    language: 'Language',
    
    // Experimental Features
    experimentalFeatures: 'Experimental Features',
    refresh: 'Refresh',
    loadingFeatures: 'Loading...',
    failedToLoadFeatures: 'Failed to load experimental features information',
    vectorStore: 'Vector Store',
    vectorStoreDesc: 'Enable vector search and AI-powered search functionality',
    metrics: 'Metrics',
    metricsDesc: 'Enable performance metrics collection and monitoring',
    logsRoute: 'Logs Route',
    logsRouteDesc: 'Enable log viewing route',
    containsFilter: 'Contains Filter',
    containsFilterDesc: 'Enable contains filter functionality',
    editDocumentsByFunction: 'Edit Documents by Function',
    editDocumentsByFunctionDesc: 'Allow editing documents through functions',
    network: 'Network',
    networkDesc: 'Enable network-related functionality',
    chatCompletions: 'Chat Completions',
    chatCompletionsDesc: 'Enable chat completions API',
    multimodal: 'Multimodal Search',
    multimodalDesc: 'Enable multimodal search (images, audio, etc.)',
    
    // Vector Search in Project Search
    vectorSearch: 'Vector Search',
    enableVectorSearch: 'Enable Vector Search',
    semanticRatio: 'Semantic Search Ratio',
    noVectorEngineConfigured: 'No vector engine configured for this index',
    configureVectorEngineFirst: 'Please configure vector engine in index settings first',
    goToEmbeddersSettings: 'Go to Embedders Settings',

    // Task Status
    statusSucceeded: 'Succeeded',
    statusFailed: 'Failed',
    statusCanceled: 'Canceled',
    statusEnqueued: 'Enqueued',
    statusProcessing: 'Processing',

    // Attribute Settings
    searchableAttributes: 'Searchable Attributes',
    searchableAttributesDesc: 'Attributes used for search. Order determines relevance priority.',
    displayedAttributes: 'Displayed Attributes',
    displayedAttributesDesc: 'Attributes returned in search results.',
    filterableAttributes: 'Filterable Attributes',
    filterableAttributesDesc: 'Configure attributes that can be used for filtering and faceting.',
    sortableAttributes: 'Sortable Attributes',
    sortableAttributesDesc: 'Attributes that can be used for sorting search results.',

    // Ranking Rules Page
    rankingRulesDesc: 'Rules that determine the relevancy of search results. Order matters - rules are applied sequentially.',
    resetToDefault: 'Reset to Default',
    dragToReorder: 'Drag to reorder. The first rule has the most impact on relevancy.',
    addCustomRule: '+ Add Custom Rule',
    defaultRulesLabel: 'Default Rules',
    ruleWords: 'Results are ranked by the number of matching query words in descending order',
    ruleTypo: 'Results are ranked by the number of typos in ascending order',
    ruleProximity: 'Results are ranked by the distance between matching query words in ascending order',
    ruleAttribute: 'Results are ranked by attribute ranking order',
    ruleSort: 'Results are ranked by query-time determined parameters',
    ruleExactness: 'Results are ranked by the similarity of matched words to query words',

    // Synonyms Page
    synonymsDesc: 'Define synonyms so that different words return the same results.',
    addSynonym: '+ Add Synonym',
    wordPlaceholder: 'Word (e.g. happy)',
    synonymsPlaceholder: 'Synonyms, comma separated (e.g. glad, joyful)',
    synonymsExample: 'Example',
    synonymsExampleText: 'If you set synonyms for "phone" as "mobile, cellphone", searching for "phone" will also return results containing "mobile" or "cellphone".',

    // Typo Tolerance Page
    typoToleranceDesc: 'Configure how Meilisearch handles typos in search queries.',
    enableLabel: 'Enable Typo Tolerance',
    enableDesc: 'Allow matches with typos in search queries.',
    minWordOneTypo: 'Min Word Size for 1 Typo',
    minWordTwoTypos: 'Min Word Size for 2 Typos',
    disableOnWords: 'Disable on Words',
    disableOnWordsPlaceholder: 'Words to disable typo tolerance on (one per line)',
    disableOnWordsDesc: 'Typo tolerance will not apply to these words.',
    disableOnAttributes: 'Disable on Attributes',
    disableOnAttributesPlaceholder: 'Attributes to disable typo tolerance on (one per line)',
    disableOnAttributesDesc: 'Typo tolerance will not apply to these attributes.',

    // Prefix Search Page
    prefixSearchDesc: 'Prefix search allows matching documents that begin with a specific query term. For example, searching for "hel" would match "hello", "help", "helicopter", etc.',
    prefixSearchMode: 'Prefix Search Mode',
    indexingTime: 'Indexing Time (Default)',
    indexingTimeDesc: 'Prefix search data is computed during indexing. This uses more storage but provides faster search performance.',
    prefixDisabled: 'Disabled',
    prefixDisabledDesc: 'Prefix search is disabled. Only exact word matches will be returned.',
    whatIsPrefixSearch: 'What is Prefix Search?',
    prefixSearchNote: 'This setting is enabled by default and computed during indexing for optimal performance. Disabling it can reduce index size but will limit search functionality.',

    // Stop Words Page
    stopWordsDesc: 'Words that are ignored during search. Common examples: the, a, an, is, at.',
    stopWordsPlaceholder: 'Enter stop words, one per line',
    stopWordsHint: 'Stop words are ignored during search and do not contribute to relevancy scoring.',

    // Separators Page
    separatorsDesc: 'Characters used to separate words during indexing. By default, Meilisearch uses spaces and punctuation.',
    separatorTokens: 'Separator Tokens',
    separatorTokensPlaceholder: 'Characters that separate words (one per line)',
    separatorTokensHint: 'Additional characters that should be treated as word separators.',
    nonSeparatorTokens: 'Non-Separator Tokens',
    nonSeparatorTokensPlaceholder: 'Characters that should NOT separate words (one per line)',
    nonSeparatorTokensHint: 'Characters that should be kept as part of words.',

    // Dictionary Page
    dictionaryDesc: 'Custom words that Meilisearch should recognize as single terms during indexing.',
    dictionaryPlaceholder: 'Enter dictionary words/patterns, one per line',
    dictionaryHint: 'Patterns defined here will be treated as unique words during indexing.',

    // Pagination Page
    paginationDesc: 'Configure the maximum number of hits a search query can return.',
    maxTotalHits: 'Max Total Hits',
    paginationHint: 'Default: 1000. Higher values may affect performance.',

    // Faceting Page
    facetingDesc: 'Configure the maximum number of values returned per facet in search results.',
    maxValuesPerFacet: 'Max Values Per Facet',
    facetingHint: 'Default: 100. Maximum number of different values per facet.',
    sortFacetValuesBy: 'Sort Facet Values By',
    alphabetically: 'Alphabetically (alpha)',
    byCount: 'By count (count)',

    // Search Cutoff Page
    searchCutoffDesc: 'Configure the maximum duration of a search query in milliseconds. Meilisearch will stop searching after this time and return the best results found.',
    cutoffDuration: 'Search Cutoff (milliseconds)',
    cutoffHint: 'Meilisearch will interrupt any search taking longer than this value. Default is 1500ms.',
    disableCutoff: 'Disable search cutoff (searches will run until completion)',
    recommendedValues: 'Recommended Values',
    rec1500: 'Default, suitable for most use cases',
    rec500: 'For real-time search with strict latency requirements',
    rec3000: 'For complex queries on large datasets',
    recNull: 'Disable cutoff (not recommended for production)',

    // Embedders Page
    embeddersDesc: 'Configure vector embedders for AI-powered search.',
    addEmbedder: 'Add Embedder',
    noEmbedders: 'No Embedders Configured',
    noEmbeddersDesc: 'Embedders generate vector data from your documents for AI-powered semantic search.',
    editEmbedder: 'Edit Embedder',
    deleteEmbedder: 'Delete Embedder',
    embedderName: 'Embedder Name *',
    embedderNameHint: 'Unique identifier for this embedder',
    sourceLabel: 'Source *',
    modelLabel: 'Model',
    dimensionsLabel: 'Dimensions',
    dimensionsHint: 'Number of dimensions in the embedding vectors',
    commonSettings: 'Common Settings',
    documentTemplate: 'Document Template',
    documentTemplateMaxBytes: 'Document Template Max Bytes',
    binaryQuantized: 'Binary Quantized (irreversible)',
    deleteEmbedderConfirm: 'Are you sure you want to delete embedder',
    deleteEmbedderWarn: 'This may trigger reindexing of all documents.',
    userProvidedInfo: "With user-provided embeddings, you must include vector data in your documents' _vectors field and generate vectors for search queries manually.",
    poolingLabel: 'Pooling',
    requestTemplate: 'Request Template (JSON)',
    responseTemplate: 'Response Path (JSON)',
    updateBtn: 'Update',
    apiKeyLabel: 'API Key',
    urlOptional: 'URL (Optional)',
    urlRequired: 'URL *',
    modelRequired: 'Model *',
    apiKeyOptional: 'API Key (Optional)',

    // Extra Experimental Features
    compositeEmbedders: 'Composite Embedders',
    compositeEmbeddersDesc: 'Enable composite embedders that combine multiple embedding sources',
    getTaskDocumentsRoute: 'Task Documents Route',
    getTaskDocumentsRouteDesc: 'Enable route to retrieve documents associated with tasks',
  },
  zh: {
    // Common
    home: '首页',
    dashboard: '仪表盘',
    projects: '项目',
    settings: '设置',
    search: '搜索',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    copy: '复制',
    create: '创建',
    add: '添加',
    close: '关闭',
    loading: '加载中...',
    noData: '暂无数据',
    confirm: '确认',
    actions: '操作',
    active: '活跃',
    copyUrl: '复制地址',
    testConnection: '测试连接',
    testing: '测试中...',
    connected: '已连接',
    connectionFailed: '连接失败',
    creating: '创建中...',
    createProject: '创建项目',
    manageInstances: '管理您的 Meilisearch 实例',
    noProjects: '暂无项目',
    noProjectsDesc: '添加您的第一个 Meilisearch 实例开始使用。',
    masterApiKey: '主API密钥',
    optional: '可选',
    optionalDesc: '选填描述信息',
    required: '必填',
    notSet: '未设置',
    updated: '更新于',
    preview: '预览',
    deleting: '删除中...',
    adding: '添加中...',
    addDocuments: '添加文档',
    jsonDocuments: 'JSON文档',
    uploadFile: '上传文件',
    fetchFromUrl: '从URL获取',
    selectImportMethod: '选择导入方式',
    uploadJsonCsv: '上传 JSON 或 CSV 文件',
    fetchDocumentsFromRemoteUrl: '从远程 URL 获取文档',
    file: '文件',
    chooseFile: '选择文件',
    noFileChosen: '未选择文件',
    remoteUrl: '远程URL',
    enterValidUrl: '请输入有效URL',
    fieldPath: '字段路径',
    fieldPathPlaceholder: '例如 data.items (可选)',
    fieldPathHint: '指定响应中文档数组的路径，例如 "data.results"',
    headers: '请求头',
    headersHint: '发送请求时附带的额外请求头 (JSON格式)',
    headersPlaceholder: '{"Authorization": "Bearer ..."}',
    primaryKeyOptional: '主键（可选）',
    pasteJson: '粘贴JSON',
    upload: '上传',
    fetch: '获取',
    import: '导入',
    jsonTabLabel: 'JSON',
    fileTabLabel: '文件',
    urlTabLabel: 'URL',
    deleteConfirm: '确定要删除',
    cannotUndo: '此操作无法撤销。',
    invalidHeadersFormat: '请求头格式无效',
    failedToAddDocuments: '添加文档失败',
    projectNotFound: '项目未找到',
    projectNotFoundDesc: '您查找的项目不存在。',
    uidHint: '必须以字母开头，可包含字母、数字、下划线和连字符。',
    primaryKeyHint: '如未设置，主键将从第一个文档中推断。',
    saving: '保存中...',
    searching: '搜索中...',
    
    // Project
    addProject: '添加项目',
    projectName: '项目名称',
    projectUrl: 'Meilisearch 地址',
    apiKey: 'API密钥',
    description: '描述',
    indexes: '索引',
    documents: '文档',
    searches: '搜索',
    tasks: '任务',
    keys: 'API密钥',
    searchPreview: '搜索预览',
    searchControls: '搜索控制',
    advancedSearch: '高级搜索',
    expandSidebar: '展开侧边栏',
    collapseSidebar: '收起侧边栏',
    resizeSidebar: '拖拽调整宽度',
    
    // Index
    createIndex: '创建索引',
    indexUid: '索引名称',
    primaryKey: '主键',
    general: '基础信息',
    attributes: '属性',
    rankingRules: '排序规则',
    synonyms: '同义词',
    typoTolerance: '容错设置',
    prefixSearch: '前缀搜索',
    stopWords: '停止词',
    separators: '分隔符',
    dictionary: '字典',
    pagination: '分页',
    faceting: '分页大小',
    searchCutoff: '搜索截止',
    embedders: '向量化',
    noIndexes: '暂无索引',
    noIndexesDesc: '创建您的第一个索引以开始索引文档。',
    indexNotFound: '索引未找到',
    indexNotFoundDesc: '您查找的索引不存在。',
    deleteIndex: '删除索引',
    
    // Search
    searchDocuments: '搜索文档...',
    results: '条结果',
    noResults: '未找到结果',
    sortBy: '排序方式...',
    filters: '筛选',
    filterType: '过滤类型',
    equality: '相等比较',
    comparison: '数值比较',
    addFilterAttribute: '添加过滤字段',
    addSearchableAttribute: '添加可搜索字段',
    addDisplayedAttribute: '添加显示字段',
    addSortableAttribute: '添加可排序字段',
    attributeName: '字段名',
    filterMode: '过滤模式',
    addCondition: '添加条件',
    removeCondition: '移除条件',
    condition: '条件',
    operator: '操作符',
    value: '值',
    supportedOperators: '支持的操作符',
    noFilterAttributes: '暂无过滤字段',
    noSearchableAttributes: '暂无可搜索字段',
    noDisplayedAttributes: '暂无显示字段',
    noSortAttributes: '暂无可排序字段',
    selectAttribute: '选择字段',
    noFilterConditions: '暂无过滤条件',
    applyFilters: '应用过滤',
    noAvailableAttributes: '暂无可用字段',
    attributeAlreadyExists: '字段已存在',
    clearFilters: '清空条件',
    viewMode: '视图模式',
    enabled: '启用',
    disabled: '禁用',
    clear: '清除',
    tableView: '表格视图',
    jsonView: 'JSON视图',
    rankingScore: '相关度评分',
    copyJson: '复制JSON',
    copySuccess: '复制成功!',
    exportQuery: '导出查询',
    copyCurlCommand: '复制cURL命令',
    exportAsPostman: '导出为Postman',
    downloadRequestBody: '下载请求体',
    queryPreview: '查询预览',
    exportQueryDescription: '导出前请检查您的搜索参数。您可以直接复制查询体或以不同格式导出。',
    queryExported: '查询已导出!',
    copied: '已复制!',
    downloaded: '已下载!',
    exported: '已导出!',
    close: '关闭',
    editDocument: '编辑文档',
    deleteDocument: '删除文档',
    selectColumns: '选择列',
    selectIndex: '选择索引',
    columns: '列',
    score: '评分',
    selectAnIndex: '请选择索引',
    selectAnIndexDesc: '选择一个索引开始搜索。',
    
    // Tasks
    status: '状态',
    type: '类型',
    index: '索引',
    uid: 'UID',
    duration: '耗时',
    date: '日期',
    applyFilters: '应用筛选',
    reset: '重置',
    noTasks: '暂无任务',
    noTasksDesc: '没有符合当前筛选条件的任务。',
    taskDetails: '任务详情',
    enqueuedAt: '入队时间',
    fullDetails: '完整详情',
    error: '错误',
    showingTasks: '显示 {count} 条任务',
    loadMore: '加载更多',
    
    // Keys
    apiKeys: 'API密钥',
    createKey: '创建密钥',
    unnamedKey: '未命名密钥',
    noDescription: '暂无描述',
    copyKey: '复制密钥',
    key: '密钥',
    createdAt: '创建时间',
    expiresAt: '过期时间',
    never: '永不过期',
    noApiKeys: '暂无API密钥',
    noApiKeysDesc: '创建API密钥以访问您的Meilisearch实例。',
    createApiKey: '创建API密钥',
    name: '名称',
    uidOptional: 'UID（可选）',
    customUid: '自定义UID',
    actionsRequired: '操作权限 *',
    indexesRequired: '索引权限 *',
    indexesHint: '使用 * 表示所有索引，或用逗号分隔的索引名称',
    deleteApiKey: '删除API密钥',
    deleteApiKeyConfirm: '确定要删除此API密钥吗？此操作无法撤销。',
    
    // Settings Page
    basicInfo: '基本信息',
    saveChanges: '保存更改',
    instanceInfo: '实例信息',
    version: '版本',
    databaseSize: '数据库大小',
    healthy: '健康',
    unhealthy: '不健康',
    dangerZone: '危险区域',
    deleteProject: '删除项目',
    deleteProjectDesc: '从Meilisearch Admin中移除此项目。这不会删除实际的Meilisearch实例。',
    deleteProjectConfirm: '确定要删除此项目吗？此操作无法撤销。',
    connectionSuccess: '连接成功！',
    connectionFailedMsg: '连接失败',
    
    // Home Page
    welcomeTitle: '欢迎使用 Meilisearch Admin',
    welcomeDesc: '强大的基于Web的管理界面，用于管理您的Meilisearch实例。添加项目、管理索引、配置设置并预览搜索结果。',
    totalProjects: '项目总数',
    activeInstances: '活跃实例',
    quickAction: '快捷操作',
    viewAllProjects: '查看所有项目',
    recentProjects: '最近项目',
    viewAll: '查看全部',
    noProjectsYet: '暂无项目',
    noProjectsYetDesc: '添加您的第一个Meilisearch实例开始使用。',
    
    // Index General Page
    fieldDistribution: '字段分布',
    indexing: '索引中',
    deleteAllDocuments: '删除所有文档',
    deleteAllDocsConfirm: '确定要删除此索引中的所有文档吗？',
    deleteAll: '全部删除',
    deleteIndexConfirm: '确定要删除此索引吗？此操作无法撤销。',
    
    // Theme
    theme: '主题',
    themeTech: '科技蓝',
    themePink: '粉红',
    themeDark: '暗黑',
    themeLight: '明亮',
    language: '语言',
    
    // Experimental Features
    experimentalFeatures: '实验性功能',
    refresh: '刷新',
    loadingFeatures: '加载中...',
    failedToLoadFeatures: '无法加载实验性功能信息',
    vectorStore: '向量存储',
    vectorStoreDesc: '启用向量搜索和AI驱动的搜索功能',
    metrics: '指标监控',
    metricsDesc: '启用性能指标收集和监控',
    logsRoute: '日志路由',
    logsRouteDesc: '启用日志查看路由',
    containsFilter: '包含过滤器',
    containsFilterDesc: '启用包含过滤器功能',
    editDocumentsByFunction: '函数编辑文档',
    editDocumentsByFunctionDesc: '允许通过函数编辑文档',
    network: '网络功能',
    networkDesc: '启用网络相关功能',
    chatCompletions: '聊天补全',
    chatCompletionsDesc: '启用聊天补全API',
    multimodal: '多模态搜索',
    multimodalDesc: '启用多模态搜索（图像、音频等）',
    
    // Vector Search in Project Search
    vectorSearch: '向量搜索',
    enableVectorSearch: '启用向量搜索',
    semanticRatio: '语义搜索比例',
    keywordSearch: '关键词搜索',
    semanticSearch: '语义搜索',
    selectEmbedder: '选择嵌入器',
    hybridSearchInfo1: '混合搜索结合关键词匹配和语义理解',
    hybridSearchInfo2: '语义比例越高，越注重内容含义而非字面匹配',
    hybridSearchInfo3: '需要先在Embedders中配置嵌入器',
    noVectorEngineConfigured: '该索引未配置向量引擎',
    configureVectorEngineFirst: '请先在索引设置中配置向量引擎',
    goToEmbeddersSettings: '前往向量嵌入设置',

    // Task Status
    statusSucceeded: '成功',
    statusFailed: '失败',
    statusCanceled: '已取消',
    statusEnqueued: '排队中',
    statusProcessing: '处理中',

    // Attribute Settings
    searchableAttributes: '可搜索属性',
    searchableAttributesDesc: '用于搜索的属性。顺序决定相关性优先级。',
    displayedAttributes: '显示属性',
    displayedAttributesDesc: '在搜索结果中返回的属性。',
    filterableAttributes: '可过滤属性',
    filterableAttributesDesc: '配置可用于过滤和分面的属性。',
    sortableAttributes: '可排序属性',
    sortableAttributesDesc: '可用于搜索结果排序的属性。',

    // Ranking Rules Page
    rankingRulesDesc: '决定搜索结果排序方式的规则。顺序很重要 - 规则按顺序依次应用。',
    resetToDefault: '恢复默认',
    dragToReorder: '拖拽重新排序。第一条规则对相关性影响最大。',
    addCustomRule: '+ 添加自定义规则',
    defaultRulesLabel: '默认规则',
    ruleWords: '结果按匹配查询词的数量降序排列',
    ruleTypo: '结果按拼写错误数量升序排列',
    ruleProximity: '结果按匹配查询词之间的距离升序排列',
    ruleAttribute: '结果按属性排序顺序排列',
    ruleSort: '结果按查询时决定的参数排列',
    ruleExactness: '结果按匹配词与查询词的相似度排列',

    // Synonyms Page
    synonymsDesc: '定义同义词，使不同的词返回相同的结果。',
    addSynonym: '+ 添加同义词',
    wordPlaceholder: '词语 (例如 happy)',
    synonymsPlaceholder: '同义词，逗号分隔 (例如 glad, joyful)',
    synonymsExample: '示例',
    synonymsExampleText: '如果设置 "phone" 的同义词为 "mobile, cellphone"，搜索 "phone" 也会返回包含 "mobile" 或 "cellphone" 的结果。',

    // Typo Tolerance Page
    typoToleranceDesc: '配置 Meilisearch 如何处理搜索查询中的拼写错误。',
    enableLabel: '启用',
    enableDesc: '开启或关闭拼写容错',
    minWordOneTypo: '允许 1 个拼写错误的最小词长',
    minWordTwoTypos: '允许 2 个拼写错误的最小词长',
    disableOnWords: '禁用拼写容错的词语',
    disableOnWordsPlaceholder: '不启用拼写容错的词语（每行一个）',
    disableOnWordsDesc: '对这些词不启用拼写容错。',
    disableOnAttributes: '禁用拼写容错的属性',
    disableOnAttributesPlaceholder: '不启用拼写容错的属性（每行一个）',
    disableOnAttributesDesc: '对这些属性不启用拼写容错。',

    // Prefix Search Page
    prefixSearchDesc: '前缀搜索允许匹配以特定查询词开头的文档。例如，搜索 "hel" 会匹配 "hello"、"help"、"helicopter" 等。',
    prefixSearchMode: '前缀搜索模式',
    indexingTime: '索引时计算 (默认)',
    indexingTimeDesc: '前缀搜索数据在索引时计算。使用更多存储空间，但搜索性能更快。',
    prefixDisabled: '禁用',
    prefixDisabledDesc: '前缀搜索已禁用。仅返回精确的词语匹配结果。',
    whatIsPrefixSearch: '什么是前缀搜索？',
    prefixSearchNote: '此设置默认启用，在索引时计算以获得最佳性能。禁用后可减小索引大小，但会限制搜索功能。',

    // Stop Words Page
    stopWordsDesc: '在搜索查询中被忽略的词语。常见示例：the, a, an, is, at。',
    stopWordsPlaceholder: '每行输入一个停止词',
    stopWordsHint: '停止词在搜索时被忽略，不参与相关性评分。',

    // Separators Page
    separatorsDesc: '索引时用于分隔词语的字符。默认情况下，Meilisearch 使用空格和标点符号。',
    separatorTokens: '分隔符',
    separatorTokensPlaceholder: '每行输入一个分隔字符',
    separatorTokensHint: '应被视为词语分隔符的额外字符。',
    nonSeparatorTokens: '非分隔符',
    nonSeparatorTokensPlaceholder: '每行输入一个非分隔字符',
    nonSeparatorTokensHint: '应保留为词语一部分的字符。',

    // Dictionary Page
    dictionaryDesc: 'Meilisearch 在索引时应识别为单个术语的自定义词语。',
    dictionaryPlaceholder: '每行输入一个词语或模式',
    dictionaryHint: '此处定义的模式在索引时将被视为独立词语。',

    // Pagination Page
    paginationDesc: '配置搜索查询可返回的最大命中数。',
    maxTotalHits: '最大命中总数',
    paginationHint: '默认：1000。值越大可能影响性能。',

    // Faceting Page
    facetingDesc: '配置搜索结果中每个分面返回的最大值数。',
    maxValuesPerFacet: '每个分面的最大值数',
    facetingHint: '默认：100。每个分面不同值的最大数量。',
    sortFacetValuesBy: '分面值排序方式',
    alphabetically: '按字母排序 (alpha)',
    byCount: '按数量排序 (count)',

    // Search Cutoff Page
    searchCutoffDesc: '配置搜索查询的最大持续时间（毫秒）。Meilisearch 将在此时间后停止搜索并返回已找到的最佳结果。',
    cutoffDuration: '截止时间 (ms)',
    cutoffHint: 'Meilisearch 将中断超过此值的搜索。默认 1500ms。',
    disableCutoff: '禁用搜索截止（搜索将运行至完成）',
    recommendedValues: '推荐值',
    rec1500: '默认值，适用于大多数场景',
    rec500: '适用于有严格延迟要求的实时搜索',
    rec3000: '适用于大型数据集上的复杂查询',
    recNull: '禁用截止（不推荐用于生产环境）',

    // Embedders Page
    embeddersDesc: '配置向量嵌入器以实现 AI 驱动的搜索。',
    addEmbedder: '添加嵌入器',
    noEmbedders: '未配置嵌入器',
    noEmbeddersDesc: '嵌入器从文档生成向量数据，用于 AI 语义搜索。',
    editEmbedder: '编辑嵌入器',
    deleteEmbedder: '删除嵌入器',
    embedderName: '嵌入器名称 *',
    embedderNameHint: '此嵌入器的唯一标识',
    sourceLabel: '来源 *',
    modelLabel: '模型',
    dimensionsLabel: '维度',
    dimensionsHint: '嵌入向量的维度数',
    commonSettings: '通用设置',
    documentTemplate: '文档模板',
    documentTemplateMaxBytes: '文档模板最大字节数',
    binaryQuantized: '二值量化（不可逆）',
    deleteEmbedderConfirm: '确定要删除嵌入器',
    deleteEmbedderWarn: '这可能会触发所有文档的重新索引。',
    userProvidedInfo: '使用用户自定义嵌入时，您必须在文档的 _vectors 字段中包含向量数据，并手动为搜索查询生成向量。',
    poolingLabel: '池化方式',
    requestTemplate: '请求模板 (JSON)',
    responseTemplate: '响应路径 (JSON)',
    updateBtn: '更新',
    apiKeyLabel: 'API 密钥',
    urlOptional: 'URL（可选）',
    urlRequired: 'URL *',
    modelRequired: '模型 *',
    apiKeyOptional: 'API 密钥（可选）',

    // Extra Experimental Features
    compositeEmbedders: '组合嵌入器',
    compositeEmbeddersDesc: '启用组合嵌入器，可以组合多个嵌入源',
    getTaskDocumentsRoute: '任务文档路由',
    getTaskDocumentsRouteDesc: '启用获取任务关联文档的路由',
  }
};

export const useSettingsStore = defineStore('settings', {
  state: () => ({
    language: localStorage.getItem('language') || 'en',
    theme: localStorage.getItem('theme') || 'tech',
  }),

  getters: {
    t: (state) => (key) => {
      return translations[state.language]?.[key] || translations.en[key] || key
    },
    
    currentLanguage: (state) => state.language,
    currentTheme: (state) => state.theme,
  },

  actions: {
    setLanguage(lang) {
      this.language = lang
      localStorage.setItem('language', lang)
    },

    setTheme(theme) {
      this.theme = theme
      localStorage.setItem('theme', theme)
      this.applyTheme(theme)
    },

    applyTheme(theme) {
      const root = document.documentElement
      
      // Remove all theme classes
      root.classList.remove('theme-tech', 'theme-pink', 'theme-dark', 'theme-light')
      
      // Add new theme class
      root.classList.add(`theme-${theme}`)
    },

    initTheme() {
      this.applyTheme(this.theme)
    },
  },
})
